services:
  valorium-server:
    container_name: valorium-server
    build:
      context: ./.docker/valorium
      dockerfile: Dockerfile
    entrypoint: ./scripts/entrypoint.sh
    stdin_open: true
    tty: true
    env_file:
      - .env
    ports:
      - '25565:25565'
    volumes:
      - ./.docker/valorium/server:/home/valorium