name = "Valorium Server"
author = "Riser876 / GMalvestiti"
version = "0.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aa6157f50ab78cff1e8c3244df0b8b7d558437ea767d6f8a6cb666a4157fa132"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
