name = "Valorium Server"
author = "Riser876"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f05882a5962be1cceba1b39865241421c795aca728cc0e1c676a6aa9e6e4e40c"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
