name = "Valorium Server"
author = "Riser876"
version = "0.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb08a14b341f9001cfa3a77f5fca243401d4b01f121562799b771a92b1fd1af7"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
