name = "Valorium Server"
author = "Riser876 / GMalvestiti"
version = "0.9.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "830d15802160c54cdfdb038ae73a8158abf0ae18fd94abe10db33e263518e45c"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
