name = "Valorium Server"
author = "Riser876"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "44b314269ce8b894769a1b7add73f976f2152cc4b301af36018edd1c270135ad"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
