name = "Valorium Server"
author = "Riser876 / GMalvestiti"
version = "0.7.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e765b8fddbb2e425caa3ab7c0fbc37e581d14768835880eef8302c4442b3264"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
