name = "Valorium Server"
author = "Riser876"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dc5cbebb55db89968e1df5d3a23e48af35a800f16fa057f51e1a1f87c8e72a28"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
