name = "Valorium Server"
author = "Riser876"
version = "0.1.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aca2651479eb87bad563ed59dca0549da7253ec5d7c50e7e1355b9acbac265f7"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
