name = "Valorium Server"
author = "Riser876"
version = "0.1.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0b57454644ecb60ff389fbe26fb5f05d8fe7ffb255fb371ad553c86c6ad2a41f"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
