name = "Valorium Server"
author = "Riser876 / GMalvestiti"
version = "0.10.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "317de97cfa29bed852716b49c726fbf3b6e87a0fc3ad54b275e535875654d25f"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
