name = "Valorium Server"
author = "Riser876 / GMalvestiti"
version = "0.11.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b9c2aea83e27030408a298374710f8aa49e9c95bfc514c20e5adb3fd70b84180"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
