name = "Valorium Server"
author = "Riser876"
version = "0.3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e4f497ac5ceb5135d4cc6b6f05a649f69e4f06dc3a09c3450d299786604e0bb5"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
